import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// bg-[#E8D9C6]
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-[#E8D9C6] ">
          <div
            className="bg-scroll bg-no-repeat bg-right-top "
            style={{
              backgroundImage: 'url("/Pen.png")',
              backgroundSize: "contain",
            }}
          >
            <Navbar />
            <div className="md:pt-[55px]">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
