import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./footer";
import Navbar from "./navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "KARWAAN '24",
  description: "Generated by create next app",
};
// bg-[#E8D9C6]
export default function RootLayout({ children }) {
  var img = "/Home/penLatest.png";

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-[#E8D9C6] relative z-10">
          <div className="flex flex-row-reverse -z-10 fixed border-0 border-sky-500 right-top w-[100vw]">
            <img
              src={img}
              alt="This is an image"
              className="flex flex-row-reverse  max-h-[100vh] max-w-[50vw] min-h[50vh] right-top border-0 border-red-700"
            ></img>
          </div>
          <Navbar />
          {children}
          {/* Footer  */}
        </div>
      </body>
    </html>
  );
}
